### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by doksu** [my2ndhead/risk_manager#6]
Hi gents,

The HyperThreat App Suite doesn't seem to be under continuing development and still isn't on SplunkBase?

Thanks,
Doksu

**Comment by my2ndhead** [comment]
Hi,

the App Suite consist of three components you can find on Splunkbase (Risk Manager, Hypercrypto and Hyperbaseline).

We will upgrade the app to support 6.3 soon, as time permits.

Thanks!

**Comment by doksu** [comment]
Ah, right you are. Thanks mate.
